- name: Install golang (Darwin)
  homebrew: name=golang state=present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install golang (Debian)
  apt: name=golang state=present update_cache=yes
  when: ansible_facts['os_family'] == 'Debian' 
  become: true