- name: Install glow (Macos)
  homebrew: name=glow state=present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install glow (Debian/Arm)
  command: /bin/bash -c 'wget https://github.com/charmbracelet/glow/releases/download/v1.4.1/glow_1.4.1_linux_armv7.deb -P /tmp/; dpkg -r glow; dpkg -i /tmp/glow_1.4.1_linux_armv7.deb'
  when: 
    - ansible_facts['os_family'] == 'Debian' 
    - ansible_facts['architecture'] == 'arm7h1' or ansible_facts['architecture'] == 'arm7hn1' or ansible_facts['architecture'] == 'arm71'
  become: true

- name: Install glow (Debian/x86_64)
  command: /bin/bash -c 'wget https://github.com/charmbracelet/glow/releases/download/v1.4.1/glow_1.4.1_linux_amd64.deb -P /tmp/; dpkg -r glow; dpkg -i /tmp/glow_1.4.1_linux_amd64.deb'
  when: 
    - ansible_facts['os_family'] == 'Debian' 
    - ansible_facts['architecture'] == 'x86_64'
  become: true
