syntax on
colorscheme delek

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType python setlocal ts=2 sts=2 sw=2 expandtab

:set number
:set backspace=indent,eol,start
" highlight all matches; can be muted for current search with :nohls
:set hlsearch
" incremental search: shows next match while typing
:set is

" indentline settings
let g:indentLine_char = '⦙'
