syntax on
"colorscheme delek
set bg=dark

" default indentation
set ts=4 sw=4

" mouse selection will not start visual mode, preventing me to select text to be copied with system clipboard
set mouse-=a

autocmd FileType yaml,yml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType python,py setlocal ts=2 sts=2 sw=2 expandtab

" show line number
set number
set backspace=indent,eol,start
" highlight all matches; can be muted for current search with :nohls
set hlsearch
" incremental search: shows next match while typing
set is

" indentline settings
let g:indentLine_char = '⦙'

" always show this many lines above or below current line
set scrolloff=5

set autoindent
set smartindent
