- name: Install watchexec (macos)
  homebrew: name=watchexec state=present
  when: ansible_facts['os_family'] == 'Darwin'

# https://github.com/watchexec/watchexec/releases/download/cli-v1.17.1/watchexec-1.17.1-x86_64-unknown-linux-gnu.deb
# wget https://github.com/watchexec/watchexec/releases/download/cli-v1.17.1/watchexec-1.17.1-x86_64-unknown-linux-gnu.deb -P /tmp/
- name: Install watchexec (debian)
  command: /bin/bash -c 'wget https://github.com/watchexec/watchexec/releases/download/cli-v1.17.1/watchexec-1.17.1-armv7-unknown-linux-gnueabihf.deb -P /tmp/; dpkg -r watchexec; dpkg -i /tmp/watchexec-1.17.1-armv7-unknown-linux-gnueabihf.deb'
  when: ansible_facts['os_family'] == 'Debian' 
  become: true
