- name: Install terraform (Macos)
  homebrew: name=terraform state=present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install apt-add-repository (Debian/x86_64)
  apt: name=software-properties-common state=present
  when: 
   - ansible_facts['os_family'] == 'Debian'
   - ansible_facts['architecture'] == 'x86_64'
  become: true

- name: Add hashicorp repository key (Debian/x86_64)
  shell: 'curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -'
  when: 
   - ansible_facts['os_family'] == 'Debian' 
   - ansible_facts['architecture'] == 'x86_64'
  become: true

- name: Add repository (Debian/x86_64)
  shell: 'apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"' 
  when: 
   - ansible_facts['os_family'] == 'Debian' 
   - ansible_facts['architecture'] == 'x86_64'
  become: true

- name: Install terraform (Debian/x86_64)
  apt: name=terraform state=present update_cache=yes
  when:
   - ansible_facts['os_family'] == 'Debian'
   - ansible_facts['architecture'] == 'x86_64'
  become: true
 
# the hashicorp apt repository does not support raspbian (it only knows debian)
# so at some point I need to find out if I can use Debian directly as an OS for the Rasp
- name: Is terraform already present? (Raspbian)
  stat: path="/usr/local/bin/terraform"
  register: tf_stat

- name: Install terraform (Raspbian) (This installs 1.5.0; to reinstall, just delete /usr/local/bin/terraform manually)
  command: /bin/bash -c 'wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_arm.zip -P /tmp/; unzip /tmp/terraform_1.5.0_linux_arm.zip -d /tmp; mv /tmp/terraform /usr/local/bin; chmod +x /usr/local/bin/terraform; rm /tmp/terraform_1.5.0_linux_arm.zip'
  when:
   - not tf_stat.stat.exists
   - ansible_facts['lsb']['id'] == 'Raspbian'
  become: true
