- name: Install vim
  homebrew: name=vim state=present

- name: Check for .vimrc
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat

- name: Back up .vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Remove .vimrc
  file: name=~/.vimrc state=absent
  when: vimrc_stat.stat.exists

- name: Symlink .vimrc
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/vimrc"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link
