- name: Install jq
  homebrew: name=jq state=present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install jq
  apt: name=jq state=present update_cache=yes
  when: ansible_facts['os_family'] == 'Debian' 
  become: true
